### ISSUE TITLE
Unable to re-build ubuntu 12.10 image &  the Desktop button disabled in the GUI

### ISSUE THREAD

**Issue by OsdKnights** [clearkimura/Customizer#19]
I installed customizer using the install.sh script. I am using a host machine with Ubuntu 12.04 64-bit to customize ubuntu 12.10 32-bit ISO image. I am having the following issues with the customizer.
1. After launching the customizer and selecting the ISO (ubuntu 12.10 32-bit). The extraction happens. But however the Desktop button in the GUI is disabled after the extraction is complete
2. I am unable to re-build the ISO. I get the error saying "unable to copy initrd.img". The extracted Filesystem folder does not contain the vmlinuz and initrd files in the boot folder.

"Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  crda iw wireless-regdb
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
WARNING: The following packages cannot be authenticated!
  linux-image-3.5.0-17-generic linux-headers-3.5.0-17
  linux-headers-3.5.0-17-generic linux-headers-generic
  linux-image-extra-3.5.0-17-generic linux-image-generic
E: There are problems and -y was used without --force-yes
[!] Chroot has returned exit status
[_] Unblocking files
[_] Cleaning up
[_] Unmounting: /sys
[_] Unmounting: /proc
[_] Unmounting: /dev
[_] Verbose unmounting
ls: cannot access /home/FileSystem/boot/initrd.img-_: No such file or directory
ls: cannot access /home/FileSystem/boot/vmlinuz-_: No such file or directory
[*] Copying initrd: 
cp: cannot stat `': No such file or directory
[X] Unable to copy initrd.img
"

 Please provide me with a workaround.

**Comment by fluxer** [comment]
About your first problem, can you provide the output of:

```
ls -l /home/FileSystem/usr/share/xsessions/
```

For the Desktop button to be enabled the only condition is this directory to hold at least one file, directories and symlinks are not considered valid in this case.

About your second problem, can you provide the output of:

```
ls -l /home/FileSystem/boot/
```

, from your log I see this:

> WARNING: The following packages cannot be authenticated!
> linux-image-3.5.0-17-generic linux-headers-3.5.0-17
> linux-headers-3.5.0-17-generic linux-headers-generic
> linux-image-extra-3.5.0-17-generic linux-image-generic
> E: There are problems and -y was used without --force-yes

which prevents the initramfs update, you can workaround that by disabling the APT helper or rebuild the initramfs manually while chrooted with:

```
update-initramfs -k all -t -u
```

and your issue with rebuilding the ISO should be gone.

**Comment by OsdKnights** [comment]
Thanks for the quick response. 

For the First issue, disabled Desktop button, below is the output requested.

root@SZ71555:~/Desktop# ls -l /home/FileSystem/usr/share/xsessions/
total 8
-rw-r--r-- 1 root root 188 Sep 27 05:07 gnome.desktop
-rw-r--r-- 1 root root 185 Sep 27 05:07 ubuntu.desktop

For the second issue, 

root@SGPZ71555:~/Desktop# ls -l /home/FileSystem/boot/
total 3612
-rw-r--r-- 1 root root  853738 Oct 10 04:05 abi-3.5.0-17-generic
-rw-r--r-- 1 root root  154429 Oct 10 04:05 config-3.5.0-17-generic
drwxr-xr-x 2 root root    4096 Oct 17 23:00 grub
-rw-r--r-- 1 root root  176764 Oct 11 22:10 memtest86+.bin
-rw-r--r-- 1 root root  178944 Oct 11 22:10 memtest86+_multiboot.bin
-rw------- 1 root root 2320733 Oct 10 04:05 System.map-3.5.0-17-generic

I am using customizer behind a proxy environment. Perhaps this was the reason the re-build failed. I then tried to manually rebuild the initramfs within the chrooted terminal after setting the proxy and the issue with re-building was resolved. 

Could you pls suggest how to enable the Desktop button?

**Comment by fluxer** [comment]
The first issue is odd, can you tell me which branch did you installed - the gambas2 or gambas3? If you are not sure give me the exact command that you executed when you installed it, e.g.:

```
sudo ./install -i
```

Meanwhile you can try the command line approach (see the user guide). The thing is that the gambas3 port is not well tested and because the contributor used the build-in gambas3 to gambas2 projects convertor it may have bugs/issues which I don't know about altough I've looked at the code and it should work, I've tested it with a Ubuntu 12.10 amd64 image and it worked but haven't done in-dept tests.

The second one I would say that it's more because there were some problems with the packages rather then your proxy, can you try the same thing/customizations but first clean up the previous files and directories, if you can reproduce this with your current proxy setup and no packages errors are trown to your console then I will consider it a bug and will look into it myself, otherwise I will considered this solved. The issue however will stay open until  we solve your first issue.

**Comment by thiagojedi** [comment]
If the problem is with the Gambas3 branch, let me know and I'll have a look.

**Comment by OsdKnights** [comment]
For the first issue,

I downloaded the script from the link https://github.com/downloads/fluxer/Customizer/install.sh and installed using the command sudo ./install.sh -i

Prior to that i installed the dependencies
coreutils sed grep rsync squashfs-tools dbus xephyr genisoimage qemu imagemagick gambas2-gui gambas2-form gambas2-runtime menu git

I am able to run the xnest using the command line /opt/Customizer/CLI.sh -x. However the Desktop button in the GUI is still disabled.

For the second issue,
I am not able to re-produce it with the proxy-set up in the chrooted terminal. I guess this is not a bug. The command update-initramfs -k all -t -u failed to execute behind the firewall earlier.

**Comment by fluxer** [comment]
I believe that the first issue has been fixed in master and gambas3 branch, tested on the later. Grab the latest install script, re-install and see how it goes.

**Comment by OsdKnights** [comment]
I tried to install again using the latest install.sh script. But now i am not able to complete the installation. I ran into the error  (./install.sh -b master -i)

E: Unable to locate package gambas2-gb-form-stock
E: Unable to locate package gambas2-devel
[ERROR] Unable to install the dependencies

I then installed gambas2-devel package again and ended up with the below error. I was not able to find the gambas2-gb-form-stock package. 

Compiling and archiving binary
- Compiling
  ./install.sh: line 114: gbc3: command not found
  [ERROR] Unable to compile binary

**Comment by fluxer** [comment]
Retry, please. My bad.

**Comment by OsdKnights** [comment]
I tried to re-install. Now the installation is successful but the customizer does not launch. When i try to launch from the cmd line, i get the error

ERROR: #2: Cannot load class 'FMain': Unable to load class file

**Comment by OsdKnights** [comment]
i am still unable to install customizer successfully. I keep getting the error "cannot load class FMain:unable to load class file" although the files are present in the GUI folder. 

Should i install any specific version of Gambas-dev? I am currently using gambas2-dev_2.23.1-1ubuntu3_amd64

Am i missing something? please suggest a workaround?

**Comment by fluxer** [comment]
Well, installing from the gambas3 branch works fine here, I can not test the gambas2 (master) branch since I'm running Debian Wheezy and Gambas2 packages are not available for it (at least from the official repositories). Thus, I'm waiting for someone to test that, Mubiin would do it if he had the time but I guess he's bussy right now.

The issue is probably cause by gambas2 versions incompatibility which the latest script should have solved, apparently it doesn't OR the source code is not incompatibility with the versions Ubuntu provides for you. Either way the best I can think of is reinstall the dependencies and reinstall Customizer via the script. If that doesn't work try your luck with the gambas3 port:

```
sudo ./install -b gambas3 -i
```

**Comment by ghost** [comment]
@fluxer 

I'm following this issue thread, but not quite free to help. Anyway, I must admit that I can't help to reproduce this issue for below reasons: 
- First of all, I don't have/use any 64-bit machine at home and might not buy one at all.
  So, I'm limited to testing on 32-bit machine only.
- Secondly, to this date, I didn't test Customizer to reproduce a Unity or GNOME 3.x desktop environment, due to my aging test machine (running on 2000's single-core processor). 

Since 10.10, Ubuntu official releases DE is Unity. With Canonical removing 2D fallback mode and planning to switch completely to Compiz after 12.10, I might not bother to test with Unity after all.

To handle this kind of issues, I have one suggestion:
 we should find a volunteer for testing on 64-bit machines.

**Comment by fluxer** [comment]
Redirect your attention to issue #21 for the last problem.
